- name: pi-provisioning
  remote_user: pi
  become: true
  hosts: all
  gather_facts: true

  vars:
    - timezone: Europe/Vienna

  roles:
    - raspi-config
    - timezone
    - upgrades
    - utils
    - podman
    - unifi-controller
    - reboot
