- name: Install user utilities
  apt:
    name:
      - htop
      - neovim
      - rsync
      - unzip
      - vim
    force_apt_get: yes
    update_cache: yes
    state: latest

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
